export { default as useSettings, getGstPercent, gstInclusiveRate, getGstRate } from './hooks/useSettings';
export { default as GeneralTab } from './components/GeneralTab';
export { default as HotelInfoTab } from './components/HotelInfoTab';
export { default as RoomConfigTab } from './components/RoomConfigTab';
export { default as UsersTab } from './components/UsersTab';
export { default as NotificationsTab } from './components/NotificationsTab';
export { default as BillingTab } from './components/BillingTab';
export { default as IntegrationsTab } from './components/IntegrationsTab';
export { default as BackupSecurityTab } from './components/BackupSecurityTab';
export { default as AddUserModal } from './components/AddUserModal';
export { default as AddRoomModal } from './components/AddRoomModal';
export { default as AddTaxModal } from './components/AddTaxModal';
